### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by FaanMaario** [AntiCheatPE/AntiCheatPE#10]
Hi, your plugin is amazing but I detect falses positives hacks and ban players who did nothing.

How to fix that?

**Comment by luca28pet** [comment]
The problem of false positive as far as I know is experienced on servers with players with bad connections.
I've done sveral updates to the plugin these days and that problem can be resolved as following:
Put tags: -1 in the new config. This will disable players kicking when fly hack is detected, but the anti fly packet will be sent to the player anyway. If it is a false positive, the player will just receive the packet and do nothing; if it is a real cheater, it will disable fly hack automatically.

For speed hack there is no such packet that could do the same thing. The only alternative, if you are experiencing too many false positives, is to put points: -1 in the new config. That will completely disable speed hack detection, but it's the only way for now
