### ISSUE TITLE
Speed Detection

### ISSUE THREAD

**Issue by ghost** [AntiCheatPE/AntiCheatPE#12]
Line 101 in EventListener.php

Change the   if(($d = Main::XZDistanceSquared($event->getFrom(), $event->getTo())) > 1.4){

make > 8
or higher otherwise too sensible ant detects legits!

**Comment by fycarman** [comment]
with 8,only player with max speed will be flagged as cheaters,with medium won't. Actually,we are working on a new method for detecting speed hack.
