### ISSUE TITLE
Notice: Undefined index:

### ISSUE THREAD

**Issue by DegenApeDev** [AntiCheatPE/AntiCheatPE#9]
Getting Undefined Index errors on line 71 and 108 on the EventListener.php

Notice: Undefined index: H2O__Delirious in ~/Gensys/plugins/AntiCheatPE/src/AntiCheatPE/EventListener.php on line 108

Notice: Undefined index: pinkypie999 in ~/Genisys/plugins/AntiCheatPE/src/AntiCheatPE/EventListener.php on line 71 - this happens on kick user - > logged out due to [AntiCheat] You were kicked for using mods/hacks/cheats. Please disable them to play on this server

Also there is one on line 104 not sure when it is called. But all these are console spam.

Thanks For this plugin by the way!

**Comment by TDMidkwhatisxd** [comment]
Dang:(  ! I will take some codes to make my anticheat! Devs not active :(

**Comment by fycarman** [comment]
Remember to give credits for code. When we have time,we will update this plugin.

**Comment by fycarman** [comment]
this project is inactive.
